### ISSUE TITLE
Interactive window has odd behavior on internal exception

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/Language-Library#1]
In the pop-out console, when running a command that causes an internal exception to be generated, the "internal error" NetLogo window comes up.  After dismissing it, the console window also disappears.  Clicking the menu item to re-add it does nothing the first time, but the second time it's clicked it does come back and works as normal.  I think it would be more desirable for the window to *not* vanish on an error, but if it has to, it should come back just by clicking the menu item once.

I discovered this running the `py:runresult "os.environ['HOME']"` command, an example from the Python Basic Example models library model.  I have no idea why it's giving an exception on my system, seems like a security/permissions issue somehow.

**Comment by JamesHovet** [comment]
Hmmm, I was not able to reproduce this. 

Steps attempted:
- open the python demo file, ran setup (which does py:setup py:python and imports some libs) 
- open the interactive console, ran `import os`; ran `os.environ['HOME']`
- I got no error

I also tried to get a similar internal error to hopefully reproduce the behavior if not the cause
- open the interactive console, ran `f = open("/<path to a file that my user doesn't have permissions to open")`. 
- I got the netlogo internal error pop up but when I dismissed it, the interactive console window stayed open. 

Now that said, I think that having errors in the interactive console show up as  netlogo internal errors is a pretty bad user experience. It could make people think they did something horrible to break netlogo when really they just mistyped something or something like that. We should try our best to imitate the experience of using a standard python REPL.

**Comment by LaCuneta** [comment]
The root cause of the issue and the difference in behavior I got might be platform dependent as I was using Windows 11 to test with (and NetLogo 6.2.2 for what it's worth).  I do agree the "scary" error pop-up is likely not what we want in most cases.

**Comment by LaCuneta** [comment]
Used the latest Python extension version to re-test this and confirmed it is resolved for me with the changes.  Thanks for the fix!
