### ISSUE TITLE
Interactive window UI enhancements

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/Language-Library#2]
Here is a hodgepodge of UI enhancements for the interactive window I thought of while testing it for the Python PR:

- I think a button to run a command from the interpreter window would be handy.  The text instructions are great, but to parallel how NetLogo works, it'd make sense to have that button.  
- A way to clear the output area would be nice.  
- NetLogo's command center default is to execute on enter press.  I can see it usefulto do it either way - and it's definitely possible for foreign languages people would want to enter multi-line code quite often.  So it might be nice to have a toggle between Ctrl-Enter to run, and Enter is run with Shift-Enter for a line break (I think that's what most apps use).

**Comment by JamesHovet** [comment]
- Agree on the button for sure
- Agree on the clearing output area (Edit: I already implemented that as a right click option and just forgot about it! It should still probably be a button)
- I think especially with the button's inclusion, having that toggle is not necessary. I also think that having it harder to accidentally end your foreign language code is almost a good thing. Say you're writing a for loop, you don't want to submit until you finish writing that for loop and if it is a little bit of friction submitting that command that feels like a smaller inconvenience than the frustration of accidentally running incomplete code.
